name: Hello

on:
  push

env:
  APP_ENV : staging
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Say Hello
        run: echo "${{ secrets.APP_NAME }}"
      - name: Print Variable
        run : echo $APP_ENV